version: '3'

services:
  client:
    image: cr.yandex/crpqoulu6oud6483qllt/client:0.1.3
    ports:
      - 80:80
    network_mode: host
  server:
    image: cr.yandex/crpqoulu6oud6483qllt/server:0.1.3
    ports:
      - 8080:8080
    network_mode: host
    environment:
      APP_MONGO_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      APP_MONGO_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD} 
      APP_MONGO_HOSTNAME: localhost:27017 
      APP_ADMIN_TOKEN: ${APP_ADMIN_TOKEN}
    depends_on:
      db:
        condition: service_started
  db:
    image: mongo:7.0.7-jammy
    ports:
      - "27017:27017"
    restart: always
    network_mode: host
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE:-dumplings}
    volumes:
      - /mongo_data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 0.5s
      retries: 20
    
