version: '3'

services:
  db:
    image: mongo:7.0.7-jammy
    ports:
      - "27017:27017"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: dumplings
    networks:
      - course_work_app_network
    volumes:
      - course_work_t6_mongo_volume:/var/lib/postgresql/data
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 0.5s
      retries: 10
  s3:
    image: quay.io/minio/minio
    ports:
      - 9000:9000
      - 9090:9090
    command: ['server', '/data', '--console-address', ':9090']
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    networks:
      - course_work_app_network
    volumes:
      - course_work_s3_volume:/data
    
volumes:
  course_work_t6_mongo_volume:
  course_work_s3_volume:
networks:
  course_work_app_network:
    driver: bridge
